### ISSUE TITLE
3.11 output of ContainerAccessELBName (in os3.template.yaml) does match expected ContainerAccessELB (in openshift-main.template.yaml)

### ISSUE THREAD

**Issue by hectoralicea** [aws-quickstart/quickstart-redhat-openshift#271]
When I did a build of this stack, I got the following error:

```
Output 'ContainerAccessELB' not found in stack 'arn:aws:cloudformation:us-east-2:999999999:stack/Red-Hat-OpenShift-OpenShift3-12F3ITH7K6OSJ/f53ad4b0-202e-11eb-8cb7-06e37757564756'
```

It appears that in os3.template.yaml it generating an output called `ContainerAccessELBName`
```
  ContainerAccessELBName:
    Description: Use this ELB to expose ports to the internet
    Value: !GetAtt LoadBalancerStack.Outputs.ContainerAccessELB
```
but yet in openshift-main.template.yaml its expecting an output parameter called `ContainerAccessELB` from the GetAtt of the prior jobs output (4th line)
```
  ContainerAccessELBName:
    Condition: OS3
    Description: Use this ELB to expose ports to the internet
    Value: !GetAtt OpenShift3.Outputs.ContainerAccessELB
```

(Note:  I replaced my AWS account id with 999999999 and obfuscated stack name)
